language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0.0
  - 2.1
  - 2.2.4
env:
  matrix:
    - EMBER_VERSION="~> 1.8.0"
    - EMBER_VERSION="~> 1.9.0"
    - EMBER_VERSION="~> 1.10.0"
    - EMBER_VERSION="~> 1.11.0"
    - EMBER_VERSION="~> 1.12.0"
    - EMBER_VERSION="~> 1.13.0"
    - EMBER_VERSION="~> 2.0.0"
    - EMBER_VERSION="~> 2.1.0"
    - EMBER_VERSION="~> 2.2.0"
